pipeline {
    agent any  // Usa cualquier máquina disponible para correr el pipeline

    stages {
        stage('Preparar Entorno') {
            steps {
                sh 'pip install -r requirements.txt'  // Instala dependencias
            }
        }
        stage('Entrenar Modelo') {
            steps {
                sh 'python model.py'  // Ejecuta el script de entrenamiento
            }
        }
        stage('Generar Predicciones') {
            steps {
                sh 'python generate_predictions.py'  // Genera el predictions.json
            }
        }
        stage('Guardar Predicciones') {
            steps {
                archiveArtifacts artifacts: 'predictions/predictions.json', fingerprint: true
            }
        }
    }
}
