# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cuser_service\"5\n\x04User\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\'\n\x16\x43heckUserExistsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\":\n\x17\x43heckUserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2m\n\x0bUserService\x12^\n\x0f\x43heckUserExists\x12$.user_service.CheckUserExistsRequest\x1a%.user_service.CheckUserExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=28
  _globals['_USER']._serialized_end=81
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_start=83
  _globals['_CHECKUSEREXISTSREQUEST']._serialized_end=122
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_start=124
  _globals['_CHECKUSEREXISTSRESPONSE']._serialized_end=182
  _globals['_USERSERVICE']._serialized_start=184
  _globals['_USERSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
