# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frontend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'frontend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import notification_pb2 as notification__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\x12\x08\x66rontend\x1a\x12notification.proto\"S\n\x17NotificationListRequest\x12\x38\n\rnotifications\x18\x01 \x03(\x0b\x32!.notification.NotificationRequest\"\'\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32l\n\x0f\x46rontendService\x12Y\n\x14ReceiveNotifications\x12!.frontend.NotificationListRequest\x1a\x1e.frontend.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONLISTREQUEST']._serialized_start=48
  _globals['_NOTIFICATIONLISTREQUEST']._serialized_end=131
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=133
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=172
  _globals['_FRONTENDSERVICE']._serialized_start=174
  _globals['_FRONTENDSERVICE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
