# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_pb2 as notification__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in notification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotification = channel.unary_unary(
                '/notification.NotificationService/CreateNotification',
                request_serializer=notification__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.CreateNotificationResponse.FromString,
                _registered_method=True)
        self.CheckUserSubscribed = channel.unary_unary(
                '/notification.NotificationService/CheckUserSubscribed',
                request_serializer=notification__pb2.CheckUserSubscribedRequest.SerializeToString,
                response_deserializer=notification__pb2.CheckUserSubscribedResponse.FromString,
                _registered_method=True)
        self.SubscribeUser = channel.unary_unary(
                '/notification.NotificationService/SubscribeUser',
                request_serializer=notification__pb2.SubscribeUserRequest.SerializeToString,
                response_deserializer=notification__pb2.SubscribeUserResponse.FromString,
                _registered_method=True)
        self.UnsubscribeUser = channel.unary_unary(
                '/notification.NotificationService/UnsubscribeUser',
                request_serializer=notification__pb2.UnsubscribeUserRequest.SerializeToString,
                response_deserializer=notification__pb2.UnsubscribeUserResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserSubscribed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=notification__pb2.CreateNotificationRequest.FromString,
                    response_serializer=notification__pb2.CreateNotificationResponse.SerializeToString,
            ),
            'CheckUserSubscribed': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserSubscribed,
                    request_deserializer=notification__pb2.CheckUserSubscribedRequest.FromString,
                    response_serializer=notification__pb2.CheckUserSubscribedResponse.SerializeToString,
            ),
            'SubscribeUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeUser,
                    request_deserializer=notification__pb2.SubscribeUserRequest.FromString,
                    response_serializer=notification__pb2.SubscribeUserResponse.SerializeToString,
            ),
            'UnsubscribeUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeUser,
                    request_deserializer=notification__pb2.UnsubscribeUserRequest.FromString,
                    response_serializer=notification__pb2.UnsubscribeUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notification.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/CreateNotification',
            notification__pb2.CreateNotificationRequest.SerializeToString,
            notification__pb2.CreateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserSubscribed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/CheckUserSubscribed',
            notification__pb2.CheckUserSubscribedRequest.SerializeToString,
            notification__pb2.CheckUserSubscribedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/SubscribeUser',
            notification__pb2.SubscribeUserRequest.SerializeToString,
            notification__pb2.SubscribeUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notification.NotificationService/UnsubscribeUser',
            notification__pb2.UnsubscribeUserRequest.SerializeToString,
            notification__pb2.UnsubscribeUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
