# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"I\n\x19\x43reateNotificationRequest\x12\x14\n\x0csender_email\x18\x01 \x01(\t\x12\x16\n\x0ereceiver_email\x18\x02 \x01(\t\"-\n\x1a\x43reateNotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"+\n\x1a\x43heckUserSubscribedRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"1\n\x1b\x43heckUserSubscribedResponse\x12\x12\n\nsubscribed\x18\x01 \x01(\x08\"%\n\x14SubscribeUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"(\n\x15SubscribeUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x16UnsubscribeUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"*\n\x17UnsubscribeUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"d\n\x13NotificationRequest\x12\x14\n\x0csender_email\x18\x01 \x01(\t\x12\x16\n\x0ereceiver_email\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\x08\x32\xa4\x03\n\x13NotificationService\x12g\n\x12\x43reateNotification\x12\'.notification.CreateNotificationRequest\x1a(.notification.CreateNotificationResponse\x12j\n\x13\x43heckUserSubscribed\x12(.notification.CheckUserSubscribedRequest\x1a).notification.CheckUserSubscribedResponse\x12X\n\rSubscribeUser\x12\".notification.SubscribeUserRequest\x1a#.notification.SubscribeUserResponse\x12^\n\x0fUnsubscribeUser\x12$.notification.UnsubscribeUserRequest\x1a%.notification.UnsubscribeUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_start=36
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_end=109
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_start=111
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_end=156
  _globals['_CHECKUSERSUBSCRIBEDREQUEST']._serialized_start=158
  _globals['_CHECKUSERSUBSCRIBEDREQUEST']._serialized_end=201
  _globals['_CHECKUSERSUBSCRIBEDRESPONSE']._serialized_start=203
  _globals['_CHECKUSERSUBSCRIBEDRESPONSE']._serialized_end=252
  _globals['_SUBSCRIBEUSERREQUEST']._serialized_start=254
  _globals['_SUBSCRIBEUSERREQUEST']._serialized_end=291
  _globals['_SUBSCRIBEUSERRESPONSE']._serialized_start=293
  _globals['_SUBSCRIBEUSERRESPONSE']._serialized_end=333
  _globals['_UNSUBSCRIBEUSERREQUEST']._serialized_start=335
  _globals['_UNSUBSCRIBEUSERREQUEST']._serialized_end=374
  _globals['_UNSUBSCRIBEUSERRESPONSE']._serialized_start=376
  _globals['_UNSUBSCRIBEUSERRESPONSE']._serialized_end=418
  _globals['_NOTIFICATIONREQUEST']._serialized_start=420
  _globals['_NOTIFICATIONREQUEST']._serialized_end=520
  _globals['_NOTIFICATIONSERVICE']._serialized_start=523
  _globals['_NOTIFICATIONSERVICE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
